### PR TITLE
Visual Studio Coverage Export

### PR DESCRIPTION
**Pull request by afuzzyllama**
Added Visual Studio Coverage Export support to develop branch

### CODE REVIEW

**Comment by afuzzyllama** [comment]
The readme and wiki should be updated if this pull request is accepted :smile:

**Comment by csMACnz** [comment]
Nice one.
Can you link me to a repo or code snippet of how you would automate coverage export from Visual Studio? Or is it not scriptable?
Yes i can update the docs readme. Can't give an ETA when i'll get time to release this, sorry.

**Comment by afuzzyllama** [comment]
The following code is basically how you can do it in C#.  I've done something similar in a powershell script:
````
    using (CoverageInfo info = CoverageInfo.CreateFromFile(coverageFileName))
    {
        CoverageDS data = info.BuildDataSet();
        data.WriteXml(outputXmlFileName);
    }
```

**Comment by csMACnz** [comment]
I've created a pre-release for this for you to test that it meets your needs :)

https://www.nuget.org/packages/coveralls.net/0.7.0-beta0001

**Comment by afuzzyllama** [comment]
Thanks! This will make it easier to integrate on my build agent :)

**Pull request merged**
