### PR TITLE
Update to be multitargeted. Currently does not support netcore3+

### PR DESCRIPTION
**Pull request by thedonmon**
This change is [Reviewable](https://reviewable.io/reviews/csmacnz/coveralls.net/96)

### CODE REVIEW

**Comment by thedonmon** [comment]
Any chance u can use your nuget credentials instead of `dotnet publish` ? Will allow for the nuget package to truly be multitargeted.

**Comment by csMACnz** [comment]
I've already made changes for core 3.1 in a release branch, just need to fix the push to night step, and will have that out for testing.

Apologies for the delay on this

**Comment by csMACnz** [comment]
I've just pushed [2.0.0-beta0002](https://www.nuget.org/packages/coveralls.net/2.0.0-beta0002) to nuget.

Let me know if you hve any issues.

**Comment by thedonmon** [comment]
Awesome will check it out forsure and let you know. Thank you sir!

**Pull request closed without merging**
