### PR TITLE
Upgrade to dotnet5

### PR DESCRIPTION
**Pull request by csMACnz**
replaces #103 onto master

This change is [Reviewable](https://reviewable.io/reviews/csmacnz/coveralls.net/105)

### CODE REVIEW

**Comment by csMACnz** [comment]
waiting on this issue to close:
https://github.com/appveyor/ci/issues/3571

**Comment by johanhugg** [comment]
👍

**Review by csMACnz — COMMENTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/csmacnz/coveralls.net/105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @csMACnz)

**Comment by bomehlsen** [comment]
@csMACnz any idea about when this will be released? Anything we can do to help get it released?

**Comment by csMACnz** [comment]
@bomehlsen working on it, just verifying some docs and version numbers...

**Comment by bomehlsen** [comment]
@csMACnz any news on a release?

**Comment by csMACnz** [comment]
So sorry @bomehlsen I started the release in december then got totally sidetracked on non-IT projects in my southern-hemisphere summer... and my automation had failed me. I have not manually pushed the github release notes and (crucially) nuget.org package for version 3.0.0 🙇 thanks for your patients!

**Comment by bomehlsen** [comment]
@csMACnz - It's all good. Thanks for your good work.

**Pull request merged**
