### PR TITLE
Pull request support

### PR DESCRIPTION
**Pull request by AndersAbel**
Added support for coveralls pull request. PR number can either be specified on command line or picked up from appveyor.

Based on #39.

I have successfully set this up on a repo I'm working on. Please see https://coveralls.io/github/KentorIT/authservices for example, where the pull requests have status updates from coveralls. An example is https://github.com/KentorIT/authservices/pull/360 where the green check mark on the last commit shows coverall and appveyor statuses.

I also fixed a couple of minor typos and added a status printout on successful upload. I found it hard to know if the upload had been run or not during build without it. Please let me know if you don't like those things and I'll drop them from the PR.

### CODE REVIEW

**Comment by csMACnz** [comment]
This all looks reasonable, but sorry to be a pain, can you rebase this against the develop branch instead of master?  I'm using gitflow for version releases.
Thanks.

Also, I didn't realise that the PR builds worked using evironment variables hidden inside appveyor. I assume you are not using secure variables for the coveralls.io key on your internal appveyor config settings? (Just FYI, if they are unsecure, that means I could possibly raise a PR that exposes them if i tried?)

**Comment by AndersAbel** [comment]
I'll rebase tomorrow, no problems. (I think that if you change the default branch in the settings of the project, future PRs will go there automatically.)

Handling of the coveralls.io key securely was not obvious. Using a secure environment variable wouldn't work as they are not shown for PRs. Putting it in an environment in the appveyor web UI would work, but with appveyor.yml in the repo it would be trivial for anyone to change the build script to echo out the key to the build console. What I ended up doing was to move the key to an environment variable and dropping the appveyor.yml file completely. Instead I'm configuring everything in the web UI. Only I can change the build settings, so the key won't be exposed. Using an environment variable was necessary to keep the key from being echoed out on the build console.

I'm planning a blog post on https://coding.abel.nu where I'll provide more details, but if this can be brought in to a release fairly soon I'd wait for that before publishing.

**Comment by csMACnz** [comment]
Ok, I assume you have the `Ignore appveyor.yml` box ticked as well? Then you're probably secure enough.

image

I find there are a few benefits for using the config file over the web ui:
* Each branch can have different build config, so master and develop can have different build scripts evolving without breaking each other.
* I have a backup of the ui settings in source control, including a history
* I can tweak the build settings and test (most) of them against PRs before i commit the changes.

The downside is obviosly I can't have coveralls publish results without exposing my key.


Also you mention the default branch thing. I prefer repos to have the default branch match the version of code in the latest release, so if i need to inspect the source something it defaults to the right source, not a future unreleased state. But thats just me :)

**Comment by AndersAbel** [comment]
Yes, I've checked the ignore appveyor.yml box.

I also do see a lot of advantages of having the config in a file instead of on the web interface, but I couldn't figure out a way to keep the coveralls key secret, and working PR coverage metrics and having the config in a file.

I've rebased on develop now.

**Comment by csMACnz** [comment]
Also, looks like the "its" => "it's" change has broken one or two of the help verification tests.

**Comment by AndersAbel** [comment]
My bad, didn't even think of running the tests after the typo fix. Just pushed a fix to the tests.

**Comment by csMACnz** [comment]
Also your PR is still against master... You'll have to close this one and re-open another against develop.

**Comment by AndersAbel** [comment]
Of course. I rebased, but that's not the same.

**Pull request closed without merging**
