### PR TITLE
Issue #8 support NCover

### PR DESCRIPTION
**Pull request by SteveGilham**
Following the lead of existing coverage types, an implementation that reads the classic NCover format.

The data samples are drawn from having built the existing sample code against .net 2.0 and running under NCover 1.5.8 to guarantee the format.

The change also includes an update of the analyzers to support VS2017 version 15.5+ as the first commit in the sequence, necessary for me to be able to build the tip.

---
This change is [Reviewable](https://reviewable.io/reviews/csmacnz/coveralls.net/71)

### CODE REVIEW

**Comment by SteveGilham** [comment]
So, the Travis build is failing on the Analyzer package update, but AppVeyor was happy with it.

We can try again without it, at your discretion.

**Comment by SteveGilham** [comment]
Reverting breaks AppVeyor, as expected.  Travis reveals that I have a file name casing error.

**Comment by SteveGilham** [comment]
So, having resolved the casing issue for the NCover 1.5.8 output files, we're left with Travis still wanting an earlier analyzer version than AppVeyor, and that's going to affect all builds, not just mine.

**Comment by csMACnz** [comment]
Thanks for all that work Steve, I will take a look when I can. (Since it is December, that should be more doable I hope.)
Sorry, I was possibly aready in an unknown state in develop as I was refactoring into core. Apologies if this impacted on trying to contribute.

**Comment by csMACnz** [comment]
Thanks
I just started fighting with VS 15.5.1 and the compat analyzer stuff on another project this week. I am a bit surprised appveyor jumped on board so quickly, but hopefully in another few commits I can get travis to pass with the new version, as well.

Merging this as it seems clean and correct in itself. 👍

**Comment by csMACnz** [comment]
develop builds are green again :)

**Pull request merged**
