### PR TITLE
upgrade to dotnet5

### PR DESCRIPTION
**Pull request by johanhugg**
Quite ugly code but didn't really find a better way to do it..

---
This change is [Reviewable](https://reviewable.io/reviews/csmacnz/coveralls.net/103)

### CODE REVIEW

**Comment by johanhugg** [comment]
Not sure about the appveyor stuff :)

**Comment by csMACnz** [comment]
Thanks for the contribution @johanhugg . I'm in the middle of moving onto trunk-based development, so will make this upgrade the first thing i do to test that out. :+1: 🦖

**Comment by csMACnz** [comment]
Looks like an issue with both me configuring a fixed version of appveyor, and appveyor not supporting the RTM of .Net 5 yet.

**Comment by csMACnz** [comment]
Sorry that wasn't an intentional close, I deleted the develop branch after merging all outstanding changes to master. I can either cherrypick this into a new PR or feel free to open another against master if you prefer.

**Pull request closed without merging**
